name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've thought about
      placeholder: I considered using X, but...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a real-world scenario where this would be useful
      placeholder: |
        When coordinating agents on a large project, I need...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Critical (blocking work)
        - High (significant impact)
        - Medium (nice to have)
        - Low (future enhancement)
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of CoorChat does this relate to?
      options:
        - Agent coordination
        - Channel integration (Redis/Discord/SignalR)
        - Task management
        - GitHub integration
        - Security/Authentication
        - CLI tool
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Technical considerations or suggestions
      placeholder: |
        This could be implemented by...
        Potential challenges: ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: This is a single, focused feature request
          required: true
